version: 2

models:
  - name: hosts
    description: >
      Dimension table containing information about Airbnb hosts, including identification details,
      Superhost status, and record timestamps.
    columns:
      - name: host_id
        description: Unique identifier for the host.
        data_type: NUMBER

      - name: host_name
        description: Name of the host registered on the platform.
        data_type: VARCHAR

      - name: is_superhost
        description: Indicates whether the host has Superhost status (e.g., 'true' or 'false').
        data_type: VARCHAR

      - name: created_at
        description: Timestamp when the host record was created.
        data_type: TIMESTAMP_NTZ
        
      - name: updated_at
        description: Timestamp when the host record was last updated.
        data_type: TIMESTAMP_NTZ
